export default {
  formPage: {
    workOrderList: 'Work Order List',
    workOrderCount: '{count} items',
    statusPending: 'Pending',
    statusAssigned: 'Assigned',
    statusProcessing: 'Processing',
    statusCompleted: 'Completed',
    statusCancel: 'Cancelled',
    orderDetail: 'Order Detail',
    dispatch: 'Dispatch',
    selectHandler: 'Select Handler',
    dispatchRemark: 'Dispatch Remark',
    dispatchRemarkPlaceholder: 'Enter dispatch remark',
    dispatchSuccess: 'Dispatch Success',
    dispatchFailed: 'Dispatch Failed',
    noData: 'No work orders',
    searchPlaceholder: 'Search',
    filterByStatus: 'Status',
  },
};
